baseURL: https://RL4aa.github.io/
languageCode: en-us
title: RL4AA Collaboration | Homepage
theme: PaperMod

params:
  homeInfoParams:
    Title: RL4AA Collaboration
    Content: |
      Collaboration on Reinforcement Learning for Autonomous Accelerators

      <img src="imgs/rl4aa_logo.png" align="right" width="25%"/>

      &nbsp;

      ## Find your way around the site

      - **[Announcements](/categories/announcements)** of new events and information
      - **[Publications](/categories/publications/)** about RL applied for particle accelerators
      - **[Contact](/contact/)** us to contribute or collaborate
      - **[Search](/search/)** for keywords directly 
      - **[Archive](/archives)** to see all the posts

  SocialIcons:
    - name: github
      url: https://github.com/RL4AA
    - name: discord
      url: https://discord.gg/QtBMqsjWH2

  cover:
    linkFullImages: true

  env: production
  ShowBreadCrumbs: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  author: ["RL4AA Collaboration"]
  # defaultTheme: light
  # defaultTheme: dark
  defaultTheme: auto # to switch between dark or light according to browser theme
  description: "Reinforcement Learning for Autonomous Accelerator Collaboration - https://github.com/RL4AA"
  googleAnalytics: "G-B7HRFWK04B"

menu:
  main:
    - identifier: announcements
      name: Announcements
      url: /categories/announcements
      weight: 1
    - identifier: publications
      name: Publications
      url: /categories/publications
      weight: 2
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 3
    - identifier: archives
      name: Archive
      url: /archives/
      weight: 4
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 5

outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary

markup:
  goldmark:
    renderer:
      unsafe: true
