baseURL: https://RL4aa.github.io/
languageCode: en-us
title: RL4AA Collaboration | Homepage
theme: PaperMod

params:
  homeInfoParams:
    Title: RL4AA Collaboration
    Content: Collaboration on Reinforcement Learning for Autonomous Accelerator 
  
  SocialIcons:
    - name: github
      url: https://github.com/RL4AA

  cover:
    linkFullImages: true

  env: production
  ShowBreadCrumbs: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  author: ["RL4AA Collaboration"]
  # defaultTheme: light
  # defaultTheme: dark
  defaultTheme: auto # to switch between dark or light according to browser theme

menu: 
  main:
    - identifier: announcement
      name: Announcement
      url: /categories/announcement
      weight: 1
    - identifier: foobar
      name: Foobar
      url: /categories/foobar
      weight: 2
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 3
    - identifier: archives
      name: Archive
      url: /archives/
      weight: 4
    - identifier: search
      name: Search
      url: /search/

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary
